DECLARE
  CURSOR C1 IS SELECT CODPEDIDO, DATAPEDIDO, VALORTOTAL, DESCONTO FROM PEDIDO FOR UPDATE OF DESCONTO;
  CURSOR C3(PPEDIDO IN NUMBER) IS
    SELECT
      IP.CODPRODUTO,PRO.DESCRICAO DESCRICAO ,IP.QUANTIDADE QUANTIDADE, IP.VALORUNITARIO
    FROM PRODUTO PRO
      INNER JOIN ITEMPEDIDO IP ON IP.CODPRODUTO = PRO.CODPRODUTO
      --INNER JOIN PEDIDO P ON IP.CODPEDIDO = P.CODPEDIDO
      WHERE IP.CODPEDIDO = PPEDIDO;
  VCURSOR C1%ROWTYPE;
  RC3 C3%ROWTYPE;
  vDesconto float;
  vPct float;
  vValor float;
  vValorDescontado float;
  vValorFinalDesconto float;
BEGIN
    --ALTER TABLE PEDIDO
    --ADD DESCONTO FLOAT;
OPEN C1;
LOOP
  FETCH C1 INTO VCURSOR;
  EXIT WHEN C1%NOTFOUND;
  vDesconto := 0;
  vPct := 0;
  vValor := 0;
  vValorDescontado := 0;
  vValorFinalDesconto := 0;
  OPEN C3(VCURSOR.CODPEDIDO);
  LOOP
    FETCH C3 INTO RC3;
    EXIT WHEN C3%NOTFOUND;
    vPct := RC3.CODPRODUTO*10;
    vValor := RC3.VALORUNITARIO*RC3.QUANTIDADE;
    vValorDescontado := vValor*(vPct/100);
    vValorFinalDesconto := vValorFinalDesconto + vValorDescontado;
  END LOOP;
  CLOSE C3;
  UPDATE PEDIDO SET DESCONTO = vValorFinalDesconto WHERE CURRENT OF C1;
  DBMS_OUTPUT.PUT_LINE('Pedido: ' || VCURSOR.CODPEDIDO || ' Data: ' || VCURSOR.DATAPEDIDO || ' Valor total: ' || VCURSOR.VALORTOTAL || ' Desconto: ' || VCURSOR.DESCONTO);
END LOOP;
CLOSE C1;
END;


