DECLARE
	vCodEndereco Endereco.CODENDERECO%type := &codigo;

	vAuxEnd Endereco.CODENDERECO%type;
	vAuxPessoa PESSOA.codigo%type;

	CURSOR cEnd(PCODIGOEND IN NUMBER := vAuxEnd ) IS 
		SELECT CODENDERECO, RUA
		FROM PESSOA 
		WHERE CODENDERECO = PCODIGOEND;

	CURSOR C2(PCODIGO IN NUMBER := vAuxPessoa ) IS 
		SELECT CODIGO, RG, NOME 
		FROM PESSOA
		WHERE CODIGO = PCODIGO;

	RC1%ROWTYPE;
	RC2%ROWTYPE;
BEGIN

	SELECT MAX(CODENDERECO) into vAuxEnd FROM Endereco;
	SELECT MAX(CODIGO) into vAuxPessoa FROM PESSOA;

	OPEN C1();
		FETCH C1 INTO RC1;
		EXIT WHEN C1%NOTFOUND;
		DBMS_OUTPUT.PUT_LINE('Código Endereço: ' || RC1.CODENDERECO || ' Rua' || RC1.RUA);
			OPEN C2(RC1.CODENDERECO)
			LOOP
				FETCH C2 INTO RC2;
				EXIT WHEN C2%NOTFOUND;
				DBMS_OUTPUT.PUT_LINE('Código: ' || RC2.CODIGO || ' RG: ' || RC2.RG || ' Nome: ' || RC2.NOME);
			END LOOP;
			CLOSE C2;
	CLOSE C1;
	EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('Código Endereço não encontrado!');
END;