/*
CREATE OR REPLACE PACKAGE FINANCEIRO IS
  FUNCTION JUROS(CODCLI IN NUMBER, PERCENTUAL IN NUMBER) RETURN NUMBER;
  FUNCTION DESCONTO(CODCLI IN NUMBER, PERCENTUAL IN NUMBER) RETURN NUMBER;
END FINANCEIRO;
*/
CREATE OR REPLACE PACKAGE BODY FINANCEIRO IS
  FUNCTION JUROS(CODCLI IN NUMBER, PERCENTUAL IN NUMBER) RETURN NUMBER IS
  VALORTOT NUMBER;
  BEGIN
    SELECT SUM(P.VALORTOTAL) INTO VALORTOT FROM PEDIDO P WHERE P.CODCLIENTE = CODCLI;
    VALORTOT := VALORTOT*(1+(PERCENTUAL)/100);
    RETURN VALORTOT;
    
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    RETURN 0;
  END;
 
 FUNCTION DESCONTO(CODCLI IN NUMBER, PERCENTUAL IN NUMBER) RETURN NUMBER IS
 VALORTOT NUMBER;
  BEGIN
    SELECT SUM(P.VALORTOTAL) INTO VALORTOT FROM PEDIDO P WHERE P.CODCLIENTE = CODCLI;
    VALORTOT := VALORTOT*(1-(PERCENTUAL)/100);
    RETURN VALORTOT;
    
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    RETURN 0;
  END;
END FINANCEIRO;

SELECT * FROM DUAL;

INSERT INTO DUAL(DUMMY) VALUES (1)




