DECLARE
  CURSOR C1 IS SELECT CODCLIENTE IDCLIENTE, NOME NOMECLIENTE
    FROM CLIENTE;
    
  CURSOR C2(PCLIENTE IN NUMBER) IS 
    SELECT
      CODPEDIDO,DATAPEDIDO, VALORTOTAL
    FROM PEDIDO
    WHERE CODCLIENTE = PCLIENTE;
    
  CURSOR C3(PPEDIDO IN NUMBER) IS
    SELECT
      PRO.DESCRICAO DESCRICAO ,IP.QUANTIDADE QUANTIDADE
    FROM PRODUTO PRO
      INNER JOIN ITEMPEDIDO IP ON IP.CODPRODUTO = PRO.CODPRODUTO
      --INNER JOIN PEDIDO P ON IP.CODPEDIDO = P.CODPEDIDO
      WHERE IP.CODPEDIDO = PPEDIDO;
    
    VCURSOR C1%ROWTYPE; --CRIA UM REGISTRO DE UMA ÚNICA LINHA, COM A ESTRUTURA DO CURSOR
    --vCodigo CLIENTE.CODCLIENTE%TYPE;
    --vNome   CLIENTE.NOMECLIENTE%TYPE;
    RC2 C2%ROWTYPE;
    RC3 C3%ROWTYPE;
BEGIN
  OPEN C1;
  LOOP
    FETCH C1 INTO VCURSOR; --Mesma coisa que FETCH C1 INTO vCodigo, vNome;
    EXIT WHEN C1%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('Cliente: ' || VCURSOR.IDCLIENTE || ' ' || VCURSOR.NOMECLIENTE);
    --DBMS_OUTPUT.PUT_LINE('Sem RowType' || vCodigo || ' ' || vNome);
    OPEN C2(VCURSOR.IDCLIENTE);
    LOOP
      FETCH C2 INTO RC2;
      EXIT WHEN C2%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Pedido: ' || RC2.CODPEDIDO || ' ' || RC2.DATAPEDIDO || ' ' || RC2.VALORTOTAL);
        OPEN C3(RC2.CODPEDIDO);
        LOOP
          FETCH C3 INTO RC3;
          EXIT WHEN C3%NOTFOUND;
          DBMS_OUTPUT.PUT_LINE('Produto: ' || RC3.DESCRICAO || ' Quantidade: ' || RC3.QUANTIDADE);
        END LOOP;
        CLOSE C3;
    END LOOP;
    DBMS_OUTPUT.NEW_LINE();
    CLOSE C2;
  END LOOP;
  CLOSE C1;
END;

SELECT
      C.CODCLIENTE IDCLIENTE, C.NOME NOMECLIENTE,PRO.DESCRICAO DESCRICAO ,IP.QUANTIDADE QUANTIDADE
FROM PRODUTO PRO
  INNER JOIN ITEMPEDIDO IP ON IP.CODPRODUTO = PRO.CODPRODUTO
  INNER JOIN PEDIDO P ON IP.CODPEDIDO = P.CODPEDIDO
  INNER JOIN CLIENTE C ON P.CODCLIENTE = C.CODCLIENTE
--WHERE IP.CODPEDIDO = 1 AND C.CODCLIENTE = 1;
ORDER BY IDCLIENTE;



--

--

DECLARE 
  CURSOR C1 IS SELECT CODCLIENTE IDCLIENTE, NOME NOMECLIENTE FROM CLIENTE;
  CURSOR P1 (PCLIENTE IN NUMBER) IS SELECT CODPEDIDO, DATAPEDIDO, VALORTOTAL FROM PEDIDO
      WHERE CODCLIENTE = PCLIENTE;
  CURSOR PROD1 (PCODPEDIDO IN NUMBER) IS SELECT P.DESCRICAO, I.QUANTIDADE 
       FROM PRODUTO P INNER JOIN ITEMPEDIDO I ON P.CODPRODUTO = I.CODPRODUTO
          WHERE I.CODPEDIDO = PCODPEDIDO;
    RC1 C1%ROWTYPE;  -- CRIA UM REGISTRO DE UMA UNICA LINHA, COM A ESTRUTURA DO CURSOR
    RP1 P1%ROWTYPE;
    RPROD PROD1%ROWTYPE;
 BEGIN
    OPEN C1;
    LOOP
       FETCH C1 INTO RC1;
       EXIT WHEN C1%NOTFOUND;
         DBMS_OUTPUT.PUT_LINE('Cliente: ' || RC1.IDCLIENTE || ' ' || RC1.NOMECLIENTE);
         OPEN P1(RC1.IDCLIENTE);
         LOOP
           FETCH P1 INTO RP1;
             EXIT WHEN P1%NOTFOUND;
           DBMS_OUTPUT.PUT_LINE('        Pedido: ' || RP1.CODPEDIDO || ' ' || RP1.DATAPEDIDO || ' ' || RP1.VALORTOTAL);
           --  IMPRESSAO DOS PRODUTOS DO PEDIDO
           OPEN PROD1(P1.CODPEDIDO);
             LOOP
              FETCH PROD1 INTO RPROD;
              EXIT WHEN PROD1%NOTFOUND;
                DBMS_OUTPUT.PUT_LINE('            Produto: ' || RPROD.DESCRICAO || ' ' || RPROD.QUANTIDADE);   
             END LOOP;
             DBMS_OUTPUT.NEW_LINE();
             CLOSE PROD1;
         END LOOP;
         DBMS_OUTPUT.NEW_LINE();
         CLOSE P1;
    END LOOP;
    CLOSE C1;
 END;
  
  
  
--SELECT P.DESCRICAO, I.QUANTIDADE FROM PRODUTO P INNER JOIN ITEMPEDIDO I ON P.CODPRODUTO = I.CODPRODUTO;  